name: "GitGuardian Shield Image Scan Action"
description: "Scan images for secrets and other issues."
author: Oliver Karstoft

inputs:
  image:
    description: |
      Image to pass to `ggshield`.
    required: true
branding:
  icon: "shield"
  color: "blue"
runs:
  using: "docker"
  image: "docker://gitguardian/ggshield:v1.31.0"
  entrypoint: /app/entrypoint.sh
  args:
    - ${{ inputs.image }}
